### ISSUE TITLE
子进程不能require

### ISSUE THREAD

**Issue by yh4922** [zy445566/ncpu#1]

**Comment by yh4922** [comment]
想使用本地模块有什么方法么

**Comment by zy445566** [comment]
> 想使用本地模块有什么方法么

你的意思是想在里面ncpu的函数里面实现require是么？

**Comment by yh4922** [comment]
> > 想使用本地模块有什么方法么
> 
> 你的意思是想在里面ncpu的函数里面实现require是么？

对的  想要在worker中使用模块执行一些代码

我现在使用  child_process.fork 来实现的 代码不太好看

**Comment by zy445566** [comment]
我是建议你require在外部require，把该准备好的数据都准备好，然后再扔进来计算，其实ncpu就当作一个纯的计算函数，我觉得会好一些，你代码能发出来么(大概了逻辑就行)，我能看看怎么帮你优化一下在ncpu里面使用。
把每个函数就做一件事，多写几个纯函数，我觉得会更佳，同时计算函数只承接多重循环或大循环之类会好些。

**Comment by yh4922** [comment]
是使用图像处理  用的 canvas 的库 
canvas.toDataURL 这个方法是同步操作 会阻塞主进程  需要放到 worker 中执行
```javascript
const child_process = require('child_process');
const {loadImage, createCanvas} = require('canvas');
const fs = require('fs');

// 通过判断是否存在 think 变量 来区分主进程和子进程
if (!!global.think) {
  // 主进程导出 ForkCanvas 类
  module.exports = class ForkCanvas {
    constructor () {
      this.child_num = 0; // 初始化子进程数量
      this.max_child = 3; // 同时最大进程数量
      this.queue = []
    }
    run (data) {
      return new Promise((resolve, reject) => {
        let callback = (result, err) => {
          if (err) reject(err)
          else resolve(result)
        }
        this.queue.push({data, callback})
        try {
          this.exec()
        } catch (err) {
          reject(err)
        }
      })
    }
    exec () {
      try {
        if (this.child_num >= this.max_child && this.queue.length) return
        let item = this.queue.shift();
        if (!item) return
        let child = child_process.fork(__filename);
        this.child_num += 1
        child.on('message', item.callback); // 收到进程回调
        child.on('error', err => item.callback(null, err));
        child.on('close', () => this.sub());
        child.send(item.data);
      } catch (err) {
        console.log('error', err)
      }
    }
    sub () {
      this.child_num -= 1
      this.exec()
    }
  }
} else {
  // 子进程接收消息
  process.on('message', async function(data){
    let {item, imgPath} = data
    let resbuff = new Buffer.from(item.img, 'base64')

    // 计算截图人脸部分
    let expan = 0.3 // 向人脸外扩展一些区域
    let boxs = item.boxes
    let boxsSize = [boxs[2] - boxs[0], boxs[3] - boxs[1]]

    // 创建画布
    let canvas = createCanvas(boxsSize[0] + (boxsSize[0]*expan*2), boxsSize[1] + (boxsSize[1]*expan*2))
    let ctx = canvas.getContext('2d')
    let image = await loadImage(resbuff)

    // 绘制内容
    ctx.drawImage(image, 0-(boxs[0]-(boxsSize[0]*expan)), 0-(boxs[1] - (boxsSize[1]*expan)))

    // 导出图像
    let baseUrl = canvas.toDataURL()
    baseUrl = baseUrl.split(',')[1]
    resbuff = Buffer.from(baseUrl, 'base64');
    fs.writeFileSync(imgPath, resbuff)

    // 返回结果
    process.send(imgPath);
    process.kill(process.pid)
  });
}
```

**Comment by yh4922** [comment]
主要是 `canvas.toDataURL()` 这个方法是同步操作

**Comment by zy445566** [comment]
> 主要是 `canvas.toDataURL()` 这个方法是同步操作

确实主要是canvas. toDataURL是只能从库里面取确实是个问题，最后我决定还是把require的功能拿出来，通过注入的方式获取全局变量，来获取require
```js
await NCPU.run(()=>{
        return require('fs') === require('fs');
  },[],{injectList:['require']}) // result: true
```
通过安装npm i ncpu@1.2.0来使用该功能，十分感谢你的提问。

**Comment by yh4922** [comment]
> 
> 确实主要是canvas. toDataURL是只能从库里面取确实是个问题，最后我决定还是把require的功能拿出来，通过注入的方式获取全局变量，来获取require
> 
> ```js
> await NCPU.run(()=>{
>         return require('fs') === require('fs');
>   },[],{injectList:['require']}) // result: true
> ```
> 
> 通过安装npm i ncpu@1.2.0来使用该功能，十分感谢你的提问。

感谢回复

有个新的问题
require注入进去 可以正常调用模块 但是有些用到c++的编译的会出现 `Module did not self-register`的报错
```javascript
NCPU.run(() => {
  let canvas = require('canvas')
  console.log(canvas)
  return !!canvas
}, [],{injectList:['require']})
```
```bash
(node:18592) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:18592) UnhandledPromiseRejectionWarning: Error: Module did not self-register: '\\?\E:\Project\daolucheck\node_modules\canvas\build\Release\canvas.node'.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\Project\daolucheck\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
(node:18592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
查了一下资料 这个好像和 `binding.gyp` 有关系 官方的`worker_threads` 也是这样

**Comment by zy445566** [comment]
> Module did not self-register

你直接用也会报吧，这和你的node版本有关系。理论上切换了node版本的话，需要重新安装编译一下canvas应该就好了吧
我这边测试了一下，我这边正常没有报你说的这个错误。

**Comment by yh4922** [comment]
应该是编译版本的问题   其他有一些原生编译的我这里也会报这个错  `serialport `
